apiVersion: v1
kind: Service
metadata:
  name: ${AKS_SERVICE}
  namespace: ${AKS_NAMESPACE}
  annotations: 
    endpoing_create: "curl -Lk https://`kubectl get svc -n $AKS_NAMESPACE | grep $AKS_APP_NAME | awk '{print $4}'`:$AKS_APP_USER_PORT/backup/create"
    endpoing_delete: "curl -Lk https://`kubectl get svc -n $AKS_NAMESPACE | grep $AKS_APP_NAME | awk '{print $4}'`:$AKS_APP_USER_PORT/backup/delete"
    endpoing_status: "curl -Lk https://`kubectl get svc -n $AKS_NAMESPACE | grep $AKS_APP_NAME | awk '{print $4}'`:$AKS_APP_USER_PORT/backup/status"

spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: ${AKS_APP_NAME}
  ports:
  - port: 25443
    targetPort: 25443