apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: webapp1-demo-shop-cluster
  region: us-east-1
  version: "1.27"

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-076afdef0f9911f16 }
      us-east-1b: { id: subnet-001ae6deda7adaf15 }

    public:
      us-east-1a: { id: subnet-065bbff8f2e547c0e }
      us-east-1b: { id: subnet-078382a4e4f2333da }

managedNodeGroups:
  - name: webapp1-demo-shop-cluster
    minSize: 3
    maxSize: 6
    desiredCapacity: 3
    instanceType: t3.micro
    labels: {role: worker}
    ssh:
      publicKeyName: deploykey
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
        albIngress: true
