apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
  labels:
    type: local
    app: example-app
  namespace: flaskapp 
spec:
  capacity:
    storage: 50Gi
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /var/lib/data
