apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc-claim
  namespace: flaskapp
  labels:
    app: example-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
