apiVersion: v1
kind: Service
metadata:
    name: "aks-e9e9"
    labels:
        app: "aks-e9e9"
spec:
    type: LoadBalancer
    ports:
    - port: 25443
      targetPort: 25443
      protocol: TCP
      name: http
    selector:
        app: "aks-e9e9"