apiVersion: v1
kind: Service
metadata:
  name: ${EKS_SERVICE}
  namespace: ${EKS_NAMESPACE}
spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: ${EKS_APP_NAME}
  ports:
  - port: 25443
    targetPort: 25443