apiVersion: v1
kind: Service
metadata:
    name: "webapp1"
    labels:
        app: "webapp1"
spec:
    type: LoadBalancer
    ports:
    - port: 25443
      targetPort: 25443
      protocol: TCP
      name: http
    selector:
        app: "webapp1"