# This file configures the $GKE_APP_NAME app which serves public web traffic on port 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $GKE_APP_NAME
  namespace: $GKE_NAMESPACE
spec:
  replicas: 3
  selector:
    matchLabels:
      app: $GKE_APP_NAME
  template:
    metadata:
      labels:
        app: $GKE_APP_NAME
    spec:
      serviceAccountName: $GKE_SERVICE_ACCOUNT
      containers:
      - name: $GKE_APP_NAME
        image: $GKE_REGION-docker.pkg.dev/$GKE_PROJECT/$GKE_PROJECT/$GKE_APP_NAME:$GITHUB_SHA
        ports:
        - containerPort: 25443
        env:
          - name: PORT
            value: "25443"
