apiVersion: v1
kind: Service
metadata:
  name: $GKE_SERVICE
  namespace: $GKE_NAMESPACE
spec:
#  serviceAccountName: $GKE_SERVICE_ACCOUNT
  type: LoadBalancer
  selector:
    app: $GKE_APP_NAME
  ports:
  - port: 25443
    targetPort: 25443